#:schema node_modules/wrangler/config-schema.json
name = "shortener"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SHORTENER_KV", id = "f88fd24effff4b3384de03d3a9dd51a9", preview_id = "d581e20bfe85442296267d960d568ef8" }
]

[vars]
HOST_URL = "https://shortener.kevinlupera.workers.dev"